baseurl: "/"
url: "https://ghosttown.live"
permalink: pretty
title: "Jenna Jones - Music PR"
collections:
  bands:
    output: true
collections_dir: collections
markdown: kramdown
highlighter: rouge

sass:
  style: compact

include: [".well-known"]

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - yarn.lock
  - package.json
  - package-lock.json
  - vendor
  - LICENSE.md
  - LICENSE
  - README.md
  - .vscode
  - .gitignore
  - .liquidrc
